
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MEDECAWebApp
{

using System;
    using System.Collections.Generic;
    
public partial class Cita
{

    public int IdCita { get; set; }

    public System.DateTime Fecha { get; set; }

    public string Hora { get; set; }

    public Nullable<int> IdVehiculo { get; set; }

    public string Cliente { get; set; }

    public string Vehiculo { get; set; }

}

}
