//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDECAWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Combustible
    {
        public Combustible()
        {
            this.Vehiculos = new HashSet<Vehiculo>();
        }
    
        public int IdCombustible { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Vehiculo> Vehiculos { get; set; }
    }
}
