//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDECAWebApp
{
    using System;
    
    public partial class HistoricoServicios
    {
        public string Info { get; set; }
        public string Placa { get; set; }
        public string Fecha { get; set; }
        public string Estado { get; set; }
        public string Cliente { get; set; }
        public string Servicios { get; set; }
        public bool Entregado { get; set; }
    }
}
