//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDECAWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsumosProveedore
    {
        public int IdProveedor { get; set; }
        public int IdInsumo { get; set; }
        public int IdOrdenServicio { get; set; }
        public decimal Precio { get; set; }
        public short Cantidad { get; set; }
    
        public virtual Insumo Insumo { get; set; }
        public virtual OrdenesTrabajo OrdenesTrabajo { get; set; }
        public virtual Proveedore Proveedore { get; set; }
    }
}
