
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MEDECAWebApp
{

using System;
    using System.Collections.Generic;
    
public partial class InsumosCotizados
{

    public int IdInsumoCotizado { get; set; }

    public int IdOrden { get; set; }

    public int IdInsumo { get; set; }

    public Nullable<int> IdProveedor { get; set; }

    public Nullable<bool> Aprobado { get; set; }

    public Nullable<decimal> Precio { get; set; }

    public Nullable<int> IdMarcaInsumo { get; set; }

    public Nullable<int> Cantidad { get; set; }

    public Nullable<bool> EsLocal { get; set; }

    public Nullable<System.DateTime> FechaCompra { get; set; }

    public Nullable<System.DateTime> FechaAproxLlegada { get; set; }



    public virtual Insumo Insumos { get; set; }

    public virtual MarcasInsumos MarcasInsumos { get; set; }

    public virtual OrdenesTrabajo OrdenesTrabajos { get; set; }

    public virtual Proveedore Proveedores { get; set; }

}

}
