
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MEDECAWebApp
{

using System;
    using System.Collections.Generic;
    
public partial class MarcasInsumos
{

    public MarcasInsumos()
    {

        this.InsumosCotizados = new HashSet<InsumosCotizados>();

    }


    public int IdMarcaInsumo { get; set; }

    public string Nombre { get; set; }



    public virtual ICollection<InsumosCotizados> InsumosCotizados { get; set; }

}

}
