//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDECAWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelo
    {
        public Modelo()
        {
            this.Vehiculos = new HashSet<Vehiculo>();
        }
    
        public int IdModelo { get; set; }
        public int IdMarca { get; set; }
        public string Nombre { get; set; }
    
        public virtual VehiculoMarca VehiculoMarca { get; set; }
        public virtual ICollection<Vehiculo> Vehiculos { get; set; }
    }
}
