//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDECAWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.Insumos = new HashSet<Insumo>();
            this.OrdenesTrabajos = new HashSet<OrdenesTrabajo>();
        }
    
        public int IdVehiculo { get; set; }
        public int IdCliente { get; set; }
        public string NoChasis { get; set; }
        public int IdModelo { get; set; }
        public int Anio { get; set; }
        public int IdCombustible { get; set; }
        public string Color { get; set; }
        public Nullable<double> Kilometraje { get; set; }
        public string Placa { get; set; }
        public string Motor { get; set; }
        public string UnidadDistancia { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Combustible Combustible { get; set; }
        public virtual Modelo Modelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Insumo> Insumos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesTrabajo> OrdenesTrabajos { get; set; }
    }
}
