
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MEDECAWebApp
{

using System;
    using System.Collections.Generic;
    
public partial class VehiculoMarca
{

    public VehiculoMarca()
    {

        this.Modelos = new HashSet<Modelo>();

    }


    public int IdMarca { get; set; }

    public string Nombre { get; set; }



    public virtual ICollection<Modelo> Modelos { get; set; }

}

}
