//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDECAWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ClientesProximasRevisiones
    {
        public Nullable<int> IdVehiculo { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string Placa { get; set; }
        public string NoChasis { get; set; }
        public Nullable<int> IdModelo { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<int> IdCombustible { get; set; }
        public string Color { get; set; }
        public Nullable<double> Kilometraje { get; set; }
        public string Motor { get; set; }
        public string UnidadDistancia { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public int OrdenId { get; set; }
        public System.DateTime FechaRecepcion { get; set; }
        public Nullable<System.DateTime> ProximaRevision { get; set; }
        public int IdEstado { get; set; }
        public int IdAlerta { get; set; }
    }
}
