//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDECAWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_OrdenesInfo
    {
        public int Id { get; set; }
        public int IdVehiculo { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> NoOrden { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> FechaPrometida { get; set; }
        public bool Entregado { get; set; }
        public Nullable<int> DaysOverdue { get; set; }
        public string Vehiculo { get; set; }
        public string Placa { get; set; }
        public Nullable<bool> ReparacionesPendientes { get; set; }
        public Nullable<bool> CotizacionesPendientes { get; set; }
    }
}
